version: "3.9"

services:
  cl_postgres:
    image: postgres:15
    container_name: cl_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  cl_backend_migrate:
    container_name: cl_postgres_migrate
    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: alembic upgrade head
    depends_on:
      - cl_postgres
    networks:
      - app-network

  cl_backend:
    container_name: cl_backend
    ports:
    - "8000:8000"

    build:
      context: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: python run.py
    depends_on:
      - cl_postgres
      - cl_backend_migrate
    networks:
      - app-network

  cl_frontend:
    container_name: cl_frontend
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - cl_backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
