apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-postgres
  namespace: ctadel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cl-postgres
  template:
    metadata:
      labels:
        app: cl-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: app_db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
