name: Auto-merge submodule update branch to master

on:
  push:
    branches:
      - sync/backend
      - sync/frontend

jobs:
  merge-to-master:
    name: Merge submodule update branch into master
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0  # Important to allow full merge
          ref: master

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add remote and fetch
        run: |
          git remote add source https://github.com/${{ github.repository }}.git
          git fetch source ${{ github.ref_name }}

      - name: Merge branch into master
        run: |
          git merge --no-ff --no-edit source/${{ github.ref_name }}

      - name: Push to master
        run: |
          git push origin master
