name: Auto-merge submodule PR

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
      - frontend/**

jobs:
  auto-merge-submodule-pr:
    name: Auto-merge submodule PR
    if: |
      (github.head_ref == 'sync/backend' || github.head_ref == 'sync/frontend') &&
      github.actor == 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          merge-method: squash
